//
//  main.swift
//  Graph
//
//  Created by Abhay Curam on 7/16/25.
//

var graph = Graph<String>()
graph.addEdge(from: "A", to: "C", weight: 2)
graph.addEdge(from: "A", to: "B", weight: 3)
graph.addEdge(from: "B", to: "D", weight: 1)
graph.addEdge(from: "B", to: "A", weight: 0)
graph.addEdge(from: "B", to: "F", weight: 5)
graph.addEdge(from: "C", to: "E", weight: 7)
graph.addEdge(from: "D", to: "B", weight: 0)
graph.addEdge(from: "D", to: "F", weight: 3)
graph.addEdge(from: "D", to: "Z", weight: 3)
graph.addEdge(from: "E", to: "F", weight: 2)
graph.addEdge(from: "E", to: "F", weight: 1)
graph.addEdge(from: "Z", to: "Z", weight: 8)
graph.addEdge(from: "Z", to: "A", weight: 5)
graph.updateValueAtVertex("A", "Abhay")
graph.updateValueAtVertex("B", "Ajay")
graph.updateValueAtVertex("C", "Pads")
graph.updateValueAtVertex("Z", "Krishna")

print(graph)
print("Reachability Testing: ")
print(graph.doesPathExist(from: "A", to: "F"))
print(graph.doesPathExist(from: "C", to: "F"))
print(graph.doesPathExist(from: "E", to: "A"))
print(graph.doesPathExist(from: "D", to: "A"))
print(graph.doesPathExist(from: "B", to: "A"))
print(graph.doesPathExist(from: "E", to: "A"))
print(graph.doesPathExist(from: "A", to: "E"))
print(graph.doesPathExist(from: "A", to: "Z"))
print(graph.doesPathExist(from: "Z", to: "A"))
print(graph.doesPathExist(from: "Z", to: "Z"))

print("Shortest Path Testing: ")
print(graph.shortestPathIgnoringWeights(from: "A", to: "F"))
print(graph.shortestPathIgnoringWeights(from: "B", to: "F"))
print(graph.shortestPathIgnoringWeights(from: "C", to: "F"))
print(graph.shortestPathIgnoringWeights(from: "B", to: "A"))
print(graph.shortestPathIgnoringWeights(from: "D", to: "A"))
print(graph.shortestPathIgnoringWeights(from: "C", to: "A"))
print(graph.shortestPathIgnoringWeights(from: "Z", to: "F"))
print(graph.shortestPathIgnoringWeights(from: "Z", to: "Z"))

print("Cycle Detection Testing: ")
let cycleGraph1 = Graph<String>()
cycleGraph1.addEdge(from: "A", to: "B", weight: 1)
cycleGraph1.addEdge(from: "A", to: "C", weight: 2)
cycleGraph1.addEdge(from: "B", to: "D", weight: 1)
cycleGraph1.addEdge(from: "B", to: "E", weight: 3)
cycleGraph1.addEdge(from: "C", to: "E", weight: 1)
cycleGraph1.addEdge(from: "D", to: "F", weight: 5)
cycleGraph1.addEdge(from: "E", to: "F", weight: 1)
print(cycleGraph1)
print(cycleGraph1.containsCycle())

let cycleGraph2 = Graph<String>()
cycleGraph2.addEdge(from: "A", to: "B", weight: 1)
cycleGraph2.addEdge(from: "A", to: "C", weight: 2)
cycleGraph2.addEdge(from: "B", to: "D", weight: 1)
cycleGraph2.addEdge(from: "B", to: "E", weight: 3)
cycleGraph2.addEdge(from: "C", to: "E", weight: 1)
cycleGraph2.addEdge(from: "D", to: "F", weight: 5)
cycleGraph2.addEdge(from: "E", to: "F", weight: 1)
cycleGraph2.addEdge(from: "F", to: "F", weight: 1)
print(cycleGraph2)
print(cycleGraph2.containsCycle())

let cycleGraph3 = Graph<String>()
cycleGraph3.addEdge(from: "A", to: "B", weight: 1)
cycleGraph3.addEdge(from: "A", to: "C", weight: 2)
cycleGraph3.addEdge(from: "B", to: "D", weight: 1)
cycleGraph3.addEdge(from: "B", to: "E", weight: 3)
cycleGraph3.addEdge(from: "C", to: "E", weight: 1)
cycleGraph3.addEdge(from: "D", to: "F", weight: 5)
cycleGraph3.addEdge(from: "E", to: "F", weight: 1)
cycleGraph3.addEdge(from: "E", to: "Z", weight: 10)
cycleGraph3.addEdge(from: "Z", to: "A", weight: 5)
print(cycleGraph3)
print(cycleGraph3.containsCycle())

let cycleGraph4 = Graph<String>()
cycleGraph4.addEdge(from: "A", to: "B", weight: 1)
cycleGraph4.addEdge(from: "A", to: "C", weight: 2)
cycleGraph4.addEdge(from: "B", to: "D", weight: 1)
cycleGraph4.addEdge(from: "B", to: "E", weight: 3)
cycleGraph4.addEdge(from: "C", to: "E", weight: 1)
cycleGraph4.addEdge(from: "D", to: "F", weight: 5)
cycleGraph4.addEdge(from: "E", to: "F", weight: 1)
cycleGraph4.addEdge(from: "G", to: "X", weight: 7)
cycleGraph4.addEdge(from: "G", to: "Z", weight: 2)
cycleGraph4.addEdge(from: "X", to: "Z", weight: 1)
print(cycleGraph4)
print(cycleGraph4.containsCycle())

let cycleGraph5 = Graph<String>()
cycleGraph5.addEdge(from: "A", to: "B", weight: 1)
cycleGraph5.addEdge(from: "A", to: "C", weight: 2)
cycleGraph5.addEdge(from: "B", to: "D", weight: 1)
cycleGraph5.addEdge(from: "B", to: "E", weight: 3)
cycleGraph5.addEdge(from: "C", to: "E", weight: 1)
cycleGraph5.addEdge(from: "D", to: "F", weight: 5)
cycleGraph5.addEdge(from: "E", to: "F", weight: 1)
cycleGraph5.addEdge(from: "G", to: "X", weight: 7)
cycleGraph5.addEdge(from: "G", to: "Z", weight: 2)
cycleGraph5.addEdge(from: "X", to: "Z", weight: 1)
cycleGraph5.addEdge(from: "X", to: "D", weight: 1)
cycleGraph5.addEdge(from: "D", to: "G", weight: 100)
print(cycleGraph5)
print(cycleGraph5.containsCycle())

let cycleGraph6 = Graph<String>()
cycleGraph6.addEdge(from: "A", to: "B", weight: 1)
cycleGraph6.addEdge(from: "A", to: "C", weight: 2)
cycleGraph6.addEdge(from: "B", to: "D", weight: 1)
cycleGraph6.addEdge(from: "B", to: "E", weight: 3)
cycleGraph6.addEdge(from: "C", to: "E", weight: 1)
cycleGraph6.addEdge(from: "D", to: "F", weight: 5)
cycleGraph6.addEdge(from: "E", to: "F", weight: 1)
cycleGraph6.addEdge(from: "G", to: "X", weight: 7)
cycleGraph6.addEdge(from: "G", to: "Z", weight: 2)
cycleGraph6.addEdge(from: "X", to: "Z", weight: 1)
cycleGraph6.addEdge(from: "Z", to: "X", weight: 1)
print(cycleGraph6)
print(cycleGraph6.containsCycle())

print("\n")
print("Now we test graph copies:")
let copiedGraph = GraphCopy.deepCopyGraph(graph)
print(graph)
print(copiedGraph)

let copiedCycleGraph1 = GraphCopy.deepCopyGraph(cycleGraph1)
print(cycleGraph1)
print(copiedCycleGraph1)

let copiedCycleGraph2 = GraphCopy.deepCopyGraph(cycleGraph2)
print(cycleGraph2)
print(copiedCycleGraph2)

let copiedCycleGraph3 = GraphCopy.deepCopyGraph(cycleGraph3)
print(cycleGraph3)
print(copiedCycleGraph3)

let copiedCycleGraph4 = GraphCopy.deepCopyGraph(cycleGraph4)
print(cycleGraph4)
print(copiedCycleGraph4)

let graph5 = Graph<String>()
graph5.addVertex("Z", "123")
graph5.addVertex("A", "64")
graph5.addEdge(from: "A", to: "A", weight: 100)
print(graph5)
print(GraphCopy.deepCopyGraph(graph5))

let binaryHeap = BinaryHeap<String>(comparatorBlock: {(lhs: String, rhs: String) -> Bool in
    return lhs < rhs
})

print("Now testing minimum cost path - Dijkstra's")
let dijkstraGraph = Graph<String>()
dijkstraGraph.addEdge(from: "A", to: "C", weight: 2)
dijkstraGraph.addEdge(from: "A", to: "B", weight: 4)
dijkstraGraph.addEdge(from: "C", to: "B", weight: 1)
dijkstraGraph.addEdge(from: "C", to: "D", weight: 4)
dijkstraGraph.addEdge(from: "C", to: "E", weight: 5)
dijkstraGraph.addEdge(from: "B", to: "C", weight: 3)
dijkstraGraph.addEdge(from: "B", to: "D", weight: 2)
dijkstraGraph.addEdge(from: "B", to: "E", weight: 3)
dijkstraGraph.addEdge(from: "E", to: "D", weight: 1)
print(dijkstraGraph)
print("Min cost path from (a, e): \(dijkstraGraph.minimumCostPath(from: "A", to: "E"))")
print("Min cost path from (a, d): \(dijkstraGraph.minimumCostPath(from: "A", to: "D"))")
print("Min cost path from (b, d): \(dijkstraGraph.minimumCostPath(from: "B", to: "D"))")
print("Min cost path from (a, b): \(dijkstraGraph.minimumCostPath(from: "A", to: "B"))")
print("Min cost path from (a, c): \(dijkstraGraph.minimumCostPath(from: "A", to: "C"))")
print("Min cost path from (e, d): \(dijkstraGraph.minimumCostPath(from: "E", to: "D"))")
print("Min cost path from (e, b): \(dijkstraGraph.minimumCostPath(from: "E", to: "B"))")
print("Min cost path from (d, a): \(dijkstraGraph.minimumCostPath(from: "D", to: "A"))")
print("Min cost path from (a, j): \(dijkstraGraph.minimumCostPath(from: "A", to: "J"))")
print("Min cost path from (j, a): \(dijkstraGraph.minimumCostPath(from: "J", to: "A"))")


let dijkstraGraph2 = Graph<String>()
dijkstraGraph2.addEdge(from: "A", to: "C", weight: 2)
dijkstraGraph2.addEdge(from: "A", to: "B", weight: 4)
dijkstraGraph2.addEdge(from: "C", to: "B", weight: 1)
dijkstraGraph2.addEdge(from: "C", to: "D", weight: 4)
dijkstraGraph2.addEdge(from: "C", to: "E", weight: 5)
dijkstraGraph2.addEdge(from: "B", to: "C", weight: 3)
dijkstraGraph2.addEdge(from: "B", to: "D", weight: 2)
dijkstraGraph2.addEdge(from: "B", to: "E", weight: 4)
dijkstraGraph2.addEdge(from: "E", to: "D", weight: 1)
print("Min cost path from (a, e): \(dijkstraGraph2.minimumCostPath(from: "A", to: "E"))")

let dijkstraMultiGraph = Graph<String>()
dijkstraMultiGraph.addEdge(from: "A", to: "C", weight: 2)
dijkstraMultiGraph.addEdge(from: "A", to: "B", weight: 4)
dijkstraMultiGraph.addEdge(from: "C", to: "B", weight: 1)
dijkstraMultiGraph.addEdge(from: "C", to: "D", weight: 4)
dijkstraMultiGraph.addEdge(from: "C", to: "E", weight: 5)
dijkstraMultiGraph.addEdge(from: "B", to: "C", weight: 3)
dijkstraMultiGraph.addEdge(from: "B", to: "D", weight: 2)
dijkstraMultiGraph.addEdge(from: "B", to: "E", weight: 3)
dijkstraMultiGraph.addEdge(from: "B", to: "E", weight: 1)
dijkstraMultiGraph.addEdge(from: "E", to: "D", weight: 1)
dijkstraMultiGraph.addEdge(from: "A", to: "A", weight: 10)
dijkstraMultiGraph.addEdge(from: "B", to: "A", weight: 2)
print("Min cost path from (a, e): \(dijkstraMultiGraph.minimumCostPath(from: "A", to: "E"))")
print("Min cost path from (a, a): \(dijkstraMultiGraph.minimumCostPath(from: "A", to: "A"))")

print("\n")
print("Topological Sort Testing, Graphs without cycles: ")
let topologicalSortGraph1 = Graph<Int>()
topologicalSortGraph1.addEdge(from: "5", to: "11", weight: 1)
topologicalSortGraph1.addEdge(from: "11", to: "2", weight: 2)
topologicalSortGraph1.addEdge(from: "11", to: "9", weight: 3)
topologicalSortGraph1.addEdge(from: "11", to: "10", weight: 4)
topologicalSortGraph1.addEdge(from: "7", to: "11", weight: 5)
topologicalSortGraph1.addEdge(from: "7", to: "8", weight: 6)
topologicalSortGraph1.addEdge(from: "3", to: "8", weight: 7)
topologicalSortGraph1.addEdge(from: "3", to: "10", weight: 8)
print(topologicalSortGraph1.getVertexIDsInTopologicalOrder())
let topologicalSortGraph2 = Graph<Int>()
topologicalSortGraph2.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph2.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph2.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph2.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph2.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph2.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph2.addEdge(from: "E", to: "F", weight: 7)
print(topologicalSortGraph2.getVertexIDsInTopologicalOrder())
let topologicalSortGraph3 = Graph<Int>()
topologicalSortGraph3.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph3.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph3.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph3.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph3.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph3.addEdge(from: "C", to: "B", weight: 5)
topologicalSortGraph3.addEdge(from: "C", to: "D", weight: 5)
topologicalSortGraph3.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph3.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph3.addEdge(from: "E", to: "D", weight: 7)
print(topologicalSortGraph3.getVertexIDsInTopologicalOrder())
let topologicalSortGraph4 = Graph<Int>()
topologicalSortGraph4.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph4.addEdge(from: "B", to: "C", weight: 2)
topologicalSortGraph4.addEdge(from: "C", to: "D", weight: 3)
topologicalSortGraph4.addEdge(from: "D", to: "E", weight: 4)
print(topologicalSortGraph4.getVertexIDsInTopologicalOrder())
let topologicalSortGraph5 = Graph<Int>()
topologicalSortGraph5.addVertex("A", 100)
print(topologicalSortGraph5.getVertexIDsInTopologicalOrder())
let topologicalSortGraph6 = Graph<Int>()
print(topologicalSortGraph6.getVertexIDsInTopologicalOrder())
let topologicalSortGraph7 = Graph<Int>()
topologicalSortGraph7.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph7.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph7.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph7.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph7.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph7.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph7.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph7.addEdge(from: "G", to: "Z", weight: 7)
topologicalSortGraph7.addEdge(from: "G", to: "X", weight: 7)
topologicalSortGraph7.addEdge(from: "X", to: "Z", weight: 7)
print(topologicalSortGraph7.getVertexIDsInTopologicalOrder())

print("\n")
print("Topological Sort Testing, Graphs without cycles: ")
let topologicalSortGraph7WithCycle = Graph<Int>()
topologicalSortGraph7WithCycle.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph7WithCycle.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph7WithCycle.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph7WithCycle.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph7WithCycle.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph7WithCycle.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph7WithCycle.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph7WithCycle.addEdge(from: "G", to: "Z", weight: 7)
topologicalSortGraph7WithCycle.addEdge(from: "G", to: "X", weight: 7)
topologicalSortGraph7WithCycle.addEdge(from: "X", to: "Z", weight: 7)
topologicalSortGraph7WithCycle.addEdge(from: "Z", to: "D", weight: 7)
topologicalSortGraph7WithCycle.addEdge(from: "F", to: "G", weight: 7)
print(topologicalSortGraph7WithCycle.getVertexIDsInTopologicalOrder())
let topologicalSortGraph5WithCycle = Graph<Int>()
topologicalSortGraph5WithCycle.addEdge(from: "A", to: "A", weight: 100)
print(topologicalSortGraph5WithCycle.getVertexIDsInTopologicalOrder())
let topologicalSortGraph1WithCycle = Graph<Int>()
topologicalSortGraph1WithCycle.addEdge(from: "5", to: "11", weight: 1)
topologicalSortGraph1WithCycle.addEdge(from: "11", to: "2", weight: 2)
topologicalSortGraph1WithCycle.addEdge(from: "11", to: "9", weight: 3)
topologicalSortGraph1WithCycle.addEdge(from: "11", to: "10", weight: 4)
topologicalSortGraph1WithCycle.addEdge(from: "7", to: "11", weight: 5)
topologicalSortGraph1WithCycle.addEdge(from: "7", to: "8", weight: 6)
topologicalSortGraph1WithCycle.addEdge(from: "3", to: "8", weight: 7)
topologicalSortGraph1WithCycle.addEdge(from: "3", to: "10", weight: 8)
topologicalSortGraph1WithCycle.addEdge(from: "11", to: "8", weight: 8)
topologicalSortGraph1WithCycle.addEdge(from: "11", to: "10", weight: 8)
topologicalSortGraph1WithCycle.addEdge(from: "10", to: "11", weight: 8)
print(topologicalSortGraph1WithCycle.getVertexIDsInTopologicalOrder())
let topologicalSortGraph3WithCycle = Graph<Int>()
topologicalSortGraph3WithCycle.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph3WithCycle.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph3WithCycle.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph3WithCycle.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph3WithCycle.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph3WithCycle.addEdge(from: "C", to: "B", weight: 5)
topologicalSortGraph3WithCycle.addEdge(from: "C", to: "D", weight: 5)
topologicalSortGraph3WithCycle.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph3WithCycle.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph3WithCycle.addEdge(from: "E", to: "D", weight: 7)
topologicalSortGraph3WithCycle.addEdge(from: "E", to: "A", weight: 7)
print(topologicalSortGraph3WithCycle.getVertexIDsInTopologicalOrder())
let topologicalSortGraph2WithCycle = Graph<Int>()
topologicalSortGraph2WithCycle.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph2WithCycle.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph2WithCycle.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph2WithCycle.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph2WithCycle.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph2WithCycle.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph2WithCycle.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph2WithCycle.addEdge(from: "F", to: "F", weight: 8)
print(topologicalSortGraph2WithCycle.getVertexIDsInTopologicalOrder())
let topologicalSortGraph2WithCycleA = Graph<Int>()
topologicalSortGraph2WithCycleA.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph2WithCycleA.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph2WithCycleA.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph2WithCycleA.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph2WithCycleA.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph2WithCycleA.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph2WithCycleA.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph2WithCycleA.addEdge(from: "A", to: "A", weight: 8)
print(topologicalSortGraph2WithCycleA.getVertexIDsInTopologicalOrder())
let topologicalSortGraph2WithCycleB = Graph<Int>()
topologicalSortGraph2WithCycleB.addEdge(from: "A", to: "B", weight: 1)
topologicalSortGraph2WithCycleB.addEdge(from: "A", to: "C", weight: 2)
topologicalSortGraph2WithCycleB.addEdge(from: "B", to: "D", weight: 3)
topologicalSortGraph2WithCycleB.addEdge(from: "B", to: "E", weight: 4)
topologicalSortGraph2WithCycleB.addEdge(from: "C", to: "E", weight: 5)
topologicalSortGraph2WithCycleB.addEdge(from: "D", to: "F", weight: 6)
topologicalSortGraph2WithCycleB.addEdge(from: "E", to: "F", weight: 7)
topologicalSortGraph2WithCycleB.addEdge(from: "B", to: "A", weight: 8)
print(topologicalSortGraph2WithCycleB.getVertexIDsInTopologicalOrder())
