//
//  main.swift
//  StringBuilder
//
//  Created by Abhay Curam on 5/21/25.
//

import Foundation

func printValueTypeMemoryAddress<T>(_ prefix: String?, _ value: inout T)
{
    withUnsafePointer(to: &value) { ptr in
        print("\(prefix ?? "") address: \(ptr)")
    }
}

func printReferenceTypeMemoryAddress<T: AnyObject>(_ prefix: String?, _ ref: T)
{
    let ptr = Unmanaged.passUnretained(ref).toOpaque()
    print("\(prefix ?? "") address: \(ptr)")
}

var s1 = SwiftStringBuilder("hello")
var s2 = s1
var s3 = s2
print("Before Value type mutation")
print("s1 toString: \(s1.toString())")
print("s2 toString: \(s2.toString())")
print("s3 toString: \(s3.toString())")
printValueTypeMemoryAddress("s1 struct", &s1)
printValueTypeMemoryAddress("s2 struct", &s2)
printValueTypeMemoryAddress("s3 struct", &s3)
printReferenceTypeMemoryAddress("s1 storage reference", s1.storage)
printReferenceTypeMemoryAddress("s2 storage reference", s2.storage)
printReferenceTypeMemoryAddress("s3 storage reference", s3.storage)
printValueTypeMemoryAddress("s1 storage character buffer array", &s1.storage.buffer)
printValueTypeMemoryAddress("s2 storage character buffer array", &s2.storage.buffer)
printValueTypeMemoryAddress("s3 storage character buffer array", &s3.storage.buffer)
print("After mutating s1 with string")
s1.append(string: " world")
print("s1 toString: \(s1.toString())")
print("s2 toString: \(s2.toString())")
print("s3 toString: \(s3.toString())")
printValueTypeMemoryAddress("s1 struct", &s1)
printValueTypeMemoryAddress("s2 struct", &s2)
printValueTypeMemoryAddress("s3 struct", &s3)
printReferenceTypeMemoryAddress("s1 storage reference", s1.storage)
printReferenceTypeMemoryAddress("s2 storage reference", s2.storage)
printReferenceTypeMemoryAddress("s3 storage reference", s3.storage)
printValueTypeMemoryAddress("s1 storage character buffer array", &s1.storage.buffer)
printValueTypeMemoryAddress("s2 storage character buffer array", &s2.storage.buffer)
printValueTypeMemoryAddress("s3 storage character buffer array", &s3.storage.buffer)
print("After mutating s2 with character")
s2.append(character: "!")
print("s1 toString: \(s1.toString())")
print("s2 toString: \(s2.toString())")
print("s3 toString: \(s3.toString())")
printValueTypeMemoryAddress("s1 struct", &s1)
printValueTypeMemoryAddress("s2 struct", &s2)
printValueTypeMemoryAddress("s3 struct", &s3)
printReferenceTypeMemoryAddress("s1 storage reference", s1.storage)
printReferenceTypeMemoryAddress("s2 storage reference", s2.storage)
printReferenceTypeMemoryAddress("s3 storage reference", s3.storage)
printValueTypeMemoryAddress("s1 storage character buffer array", &s1.storage.buffer)
printValueTypeMemoryAddress("s2 storage character buffer array", &s2.storage.buffer)
printValueTypeMemoryAddress("s3 storage character buffer array", &s3.storage.buffer)
print("------------------")

print("\n")
print("----------------")
var s6 = ObjcStringBuilder("hello")
var s7 = s6
var s8 = s7
print("Before Value type mutation")
print("s6 toString: \(s6.toString())")
print("s7 toString: \(s7.toString())")
print("s8 toString: \(s8.toString())")
printValueTypeMemoryAddress("s6 struct", &s6)
printValueTypeMemoryAddress("s7 struct", &s7)
printValueTypeMemoryAddress("s8 struct", &s8)
printReferenceTypeMemoryAddress("s6 storage reference", s6.storage)
printReferenceTypeMemoryAddress("s7 storage reference", s7.storage)
printReferenceTypeMemoryAddress("s8 storage reference", s8.storage)
print("After mutating s6 with string")
s6.append(string: " world")
print("s6 toString: \(s6.toString())")
print("s7 toString: \(s7.toString())")
print("s8 toString: \(s8.toString())")
printValueTypeMemoryAddress("s6 struct", &s6)
printValueTypeMemoryAddress("s7 struct", &s7)
printValueTypeMemoryAddress("s8 struct", &s8)
printReferenceTypeMemoryAddress("s6 storage reference", s6.storage)
printReferenceTypeMemoryAddress("s7 storage reference", s7.storage)
printReferenceTypeMemoryAddress("s8 storage reference", s8.storage)
print("After mutating s7 with character")
s7.append(character: "!")
print("s6 toString: \(s6.toString())")
print("s7 toString: \(s7.toString())")
print("s8 toString: \(s8.toString())")
printValueTypeMemoryAddress("s6 struct", &s6)
printValueTypeMemoryAddress("s7 struct", &s7)
printValueTypeMemoryAddress("s8 struct", &s8)
printReferenceTypeMemoryAddress("s6 storage reference", s6.storage)
printReferenceTypeMemoryAddress("s7 storage reference", s7.storage)
printReferenceTypeMemoryAddress("s8 storage reference", s8.storage)
print("------------------")
var s4 = ObjcStringBuilder()
print("Before Value type mutation")
print("s4 toString: \(s4.toString())")
printValueTypeMemoryAddress("s4 struct", &s4)
printReferenceTypeMemoryAddress("s4 storage reference", s4.storage)
print("After mutating string and adding char")
s4.append(character: "A")
print("s4 toString: \(s4.toString())")
printValueTypeMemoryAddress("s4 struct", &s4)
printReferenceTypeMemoryAddress("s4 storage reference", s4.storage)
print("After mutating string and adding another char")
s4.append(character: "B")
print("s4 toString: \(s4.toString())")
printValueTypeMemoryAddress("s4 struct", &s4)
printReferenceTypeMemoryAddress("s4 storage reference", s4.storage)
